Browser("Google").Page("Google").Link("Gmail").Click @@ hightlight id_;_Browser("Google").Page("Google").Link("Gmail")_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("Google").Page("Gmail - Free Storage and").Link("Create an account").Drag 142,23 @@ hightlight id_;_Browser("Google").Page("Gmail - Free Storage and").Link("Create an account")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("Google").Page("Gmail - Free Storage and").Link("Create an account").Drop 142,23 @@ hightlight id_;_Browser("Google").Page("Gmail - Free Storage and").Link("Create an account")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("Gmail - Free Storage and").Page("Gmail - Free Storage and").Link("Create an account").Click @@ hightlight id_;_Browser("Gmail - Free Storage and").Page("Gmail - Free Storage and").Link("Create an account")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebEdit("FirstName").Set "jnj" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebEdit("FirstName")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebEdit("GmailAddress").Set "jnj" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebEdit("GmailAddress")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebEdit("GmailAddress").Set "jnjemployee" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebEdit("GmailAddress")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebEdit("Passwd").SetSecure "58da44d18b515a32a932d106ba783ce8e0946f0c" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebEdit("Passwd")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebEdit("GmailAddress").Set "empjnj" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebEdit("GmailAddress")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebEdit("PasswdAgain").SetSecure "58da44e7cf7845def67f2902ecacb86ae5d4ce17" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebEdit("PasswdAgain")_;_script infofile_;_ZIP::ssf10.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebEdit("Passwd").SetSecure "58da44e99f590904108eb6f80116bd97b4d47b5ebd31" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebEdit("Passwd")_;_script infofile_;_ZIP::ssf11.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebEdit("PasswdAgain").SetSecure "58da44f2170b36dcae1546f0acbfb493be5539695c66" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebEdit("PasswdAgain")_;_script infofile_;_ZIP::ssf12.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebElement("BirthMonth").Click @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebElement("BirthMonth")_;_script infofile_;_ZIP::ssf13.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebElement("HiddenBirthMonth").Click @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebElement("HiddenBirthMonth")_;_script infofile_;_ZIP::ssf14.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebList("WebList").Select "February" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebList("WebList")_;_script infofile_;_ZIP::ssf15.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebElement("HiddenBirthMonth").Click @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebElement("HiddenBirthMonth")_;_script infofile_;_ZIP::ssf16.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebElement("birthday-placeholder").Click @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebElement("birthday-placeholder")_;_script infofile_;_ZIP::ssf17.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebEdit("BirthDay").Set "20" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebEdit("BirthDay")_;_script infofile_;_ZIP::ssf18.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebEdit("BirthYear").Set "1990" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebEdit("BirthYear")_;_script infofile_;_ZIP::ssf19.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebElement("Gender").Click @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebElement("Gender")_;_script infofile_;_ZIP::ssf20.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebElement("HiddenGender").Click @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebElement("HiddenGender")_;_script infofile_;_ZIP::ssf21.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebList("WebList_2").Select "Male" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebList("WebList 2")_;_script infofile_;_ZIP::ssf22.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebElement("HiddenGender").Click @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebElement("HiddenGender")_;_script infofile_;_ZIP::ssf23.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebEdit("RecoveryPhoneNumber").Set "" @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebEdit("RecoveryPhoneNumber")_;_script infofile_;_ZIP::ssf24.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebElement("wrapper").Click @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebElement("wrapper")_;_script infofile_;_ZIP::ssf25.xml_;_
Browser("Create your Google Account").Page("Create your Google Account").WebButton("Next step").Click @@ hightlight id_;_Browser("Create your Google Account").Page("Create your Google Account").WebButton("Next step")_;_script infofile_;_ZIP::ssf26.xml_;_
